//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonDiary.Person.DataAccess.Queries {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PersonDaoQueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PersonDaoQueries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PersonDiary.Person.DataAccess.Queries.PersonDaoQueries", typeof(PersonDaoQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from dbo.Persons where Id = @Id;.
        /// </summary>
        internal static string DeleteById {
            get {
                return ResourceManager.GetString("DeleteById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select
        ///	p.Id    &apos;Id&apos;,
        ///	p.Name    &apos;Name&apos;,
        ///	p.SurName	&apos;SurName&apos;,
        ///	p.HasFile	&apos;HasFile&apos;
        ///	from dbo.Persons p
        ///.
        /// </summary>
        internal static string GetAll {
            get {
                return ResourceManager.GetString("GetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select
        ///	p.Id    &apos;Id&apos;,
        ///	p.Name    &apos;Name&apos;,
        ///	p.SurName	&apos;SurName&apos;,
        ///	p.HasFile	&apos;HasFile&apos;
        ///	from dbo.Persons p
        ///	where df.Id = @Id;.
        /// </summary>
        internal static string GetById {
            get {
                return ResourceManager.GetString("GetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to merge dbo.Persons as p
        ///using
        ///	(select
        ///		@Id,
        ///		@Name,
        ///		@SurName,
        ///		@HasFile
        ///		) as ins (Id,Name,SurName,HasFile)
        ///on (p.id = ins.id)
        ///when matched then update set
        ///					Id = ins.Id,
        ///					Name = ins.Name,
        ///					SurName = ins.SurName
        ///when not matched then insert (Name,SurName,HasFile)
        ///					values
        ///						(ins.Id,
        ///						ins.Name,
        ///						ins.SurName,
        ///						ins.HasFile
        ///						);.
        /// </summary>
        internal static string SaveOrUpdate {
            get {
                return ResourceManager.GetString("SaveOrUpdate", resourceCulture);
            }
        }
    }
}
