USE [master]
GO

/****** Object:  Database [Person]    Script Date: 09.02.2020 17:49:58 ******/
CREATE DATABASE [Person]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Person', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQL2016\MSSQL\DATA\Person.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Person_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQL2016\MSSQL\DATA\Person_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Person].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Person] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Person] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Person] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Person] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Person] SET ARITHABORT OFF 
GO

ALTER DATABASE [Person] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Person] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Person] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Person] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Person] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Person] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Person] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Person] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Person] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Person] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Person] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Person] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Person] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Person] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Person] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Person] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Person] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Person] SET RECOVERY FULL 
GO

ALTER DATABASE [Person] SET  MULTI_USER 
GO

ALTER DATABASE [Person] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Person] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Person] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Person] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Person] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Person] SET QUERY_STORE = OFF
GO

USE [Person]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [Person] SET  READ_WRITE 
GO

